# Generated by Django 6.0 on 2025-12-18 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker_api', '0002_analysis_user_budget_user_category_user_expense_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expense_tracker_api.category'),
        ),
    ]
